title: Fernando San Segundo Barahona
description: Profesor Ayudante Doctor de la Escuela Técnica Superior de Ingeniería (ICAI), Departamento de Matemática Aplicada, Universidad Pontificia Comillas
theme: jekyll-theme-cayman