title: Fernando San Segundo Barahona
description: Profesor Ayudante Doctor de la Escuela Técnica Superior de Ingeniería (ICAI), Departamento de Matemática Aplicada, Universidad Pontificia Comillas
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
